### ISSUE TITLE
Logtailer findet kein Logfile, wenn Filerotate=0 gsetzt ist.

### ISSUE THREAD

**Issue by dc7jzb** [dg9vh/WSYSFDash#1]
Der Logtailer findet keine Logfiles, ohne Datumsextension, wie Sie vom YSFReflector generiert werden, wenn Filerotate=0 in der YSFReflector.ini gesetzt ist.

**Comment by dg9vh** [comment]
closed with https://github.com/dg9vh/WSYSFDash/commit/c44daadf0c0f9252fdc9496908942b2a43837e94
