### ISSUE TITLE
Cannot connect to websocket

### ISSUE THREAD

**Issue by jjsainzc** [dg9vh/WSYSFDash#11]
My console log
(index):475 WebSocket connection to 'ws://jjsc.ddns.net:5678/SYSINFO' failed: 
(anonymous) @ (index):475
(index):480 WebSocket connection to 'ws://jjsc.ddns.net:5678/YSFReflector' failed: 

logtailer is working
Nov  5 17:24:15 ubuntu-s-1vcpu-512mb-10gb-nyc1-01 systemd[1]: Starting Python3 logtailer for WSYSFDash...
Nov  5 17:24:25 ubuntu-s-1vcpu-512mb-10gb-nyc1-01 systemd[1]: Started Python3 logtailer for WSYSFDash.
Nov  5 17:24:26 ubuntu-s-1vcpu-512mb-10gb-nyc1-01 python3[867382]: 2023-11-05 17:24:26,059 INFO Starting Websocketserver

**Comment by dg9vh** [comment]
Did you add Portforwarding for Port 5678 TCP to your local hotspot?

**Comment by dg9vh** [comment]
Due to no reply - closed.

**Comment by jjsainzc** [comment]
Sorry I never received the email with your question, and yes the port is open in server, I don't know why you mention the hotspot, the wobsocket run in server

**Comment by dg9vh** [comment]
Sorry, wrote Hotspot, meant reflector. So you are sure traffic to 5678 tcp is going to the reflector server, where logtailer is running.

What happens on the webbrowsers Javascript console?

**Comment by jjsainzc** [comment]
Ok, Im restarted and It seem to be runnig, but I have another issue, the parsed connected gateways  are no enterily right, check this:   http://jjsc.ddns.net:8000/ and thnks in advanced

**Comment by dg9vh** [comment]
What Is the problem exactly? What reflector are you using?

**Comment by jjsainzc** [comment]
Yours 

#!/bin/bash
### YSFReflector-Installation-Script
#
# This script installes a YSFReflector on a Debian-like Linux-System
# with modification of YSFReflector.ini and creation of all necessary
# scripts to start and run the reflector.
#
# written 2018-01-15 by Kim Huebel, DG9VH
#
# Changelog:
# 2018-01-15: initial shot
#
###

**Comment by jjsainzc** [comment]
I cannot pasted the screenshot but if you see the connected gateways tabs at http://jjsc.ddns.net:8000/ you see the issue, not happend in the old dashboard using the same site but https://jjsc.ddns.net/

**Comment by dg9vh** [comment]
Connected since does only work correct, if the parsed portion of the lignite contains the connecting line or you are using pysfreflector

**Comment by jjsainzc** [comment]
Im not using pysreflector im using a C version
