### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by chuck56ri** [dg9vh/WSYSFDash#12]
TEST in the callsign column showed up on my dashboard. It had the IP of
137.226.79.115. I ran a trace and it came back with
dapnetysf.afu.rwth.aachen.de

What exacty is this?

Thanks.....
N1LMA

**Comment by dg9vh** [comment]
This is the registry Service dringend Status queries and test connectìons. This is no Dashboard issue.

You can ignore This or put it into the Blacklist.
