### ISSUE TITLE
Connected Gateway

### ISSUE THREAD

**Issue by picchiosat** [dg9vh/WSYSFDash#5]
Hi Kim, I believe there is an error in the control function of the connected gateways. Two values ​​are displayed: the first with the time of the first connection and the second line with "Connected since" "unknow" where the time changes every time the reflector writes to the log (two minutes).
You can see the problem at: https://ysf.hblink.it

Roby IV3JDV

**Comment by dg9vh** [comment]
Hi, what reflector you are using? PYSFReflector or g4klx?

Roby ***@***.***> schrieb am So., 18. Juli 2021, 12:28:

**Comment by picchiosat** [comment]
g4klx

**Comment by dg9vh** [comment]
G4klx reflector does not deliver connected since information, so there is
only the Las onlue timestamp.

Roby ***@***.***> schrieb am So., 18. Juli 2021, 16:51:
