### ISSUE TITLE
Last/All Heard not populating

### ISSUE THREAD

**Issue by chuck56ri** [dg9vh/WSYSFDash#7]
Not sure if it's a setting that's causing this but I notice the dashboard will clear all stations heard hourly. Logrotate is setup per the instructions.

**Comment by dg9vh** [comment]
Which value do you have in https://github.com/dg9vh/WSYSFDash/blob/main/logtailer.ini#L11 and which loglevel do you have set in the reflector? Which reflector-software are you using?

**Comment by chuck56ri** [comment]
pYSFReflector


[Log]
# Logging levels, 0=No logging
# not managed
DisplayLevel=1
#Set this to 0 to have full logging capabilities, 1 for normal log and 2 for very silent log
FileLevel=1
FilePath=/var/log
FileRoot=YSFReflector
# Set this to 0 and configure systems logrotate to do the job with a single log file
FileRotate=0
# Enable = 1 or disable = 0 the extended command set
EnableExtendedCommands=0



# This defines the maximum amount of loglines to be sent on initial opening of the dashboard
MaxLines=500

**Comment by dg9vh** [comment]
Is the reflector a high traffic reflector or someone with many overs within one hour? You can try experimenting with the MaxLines-paramter that says how many lines from the end of the logfile will be included in the first opening of the dashboard.

**Comment by chuck56ri** [comment]
I would not call it high traffic. Thanks for the help.
