### ISSUE TITLE
Cannot Get logtailer.py to Run

### ISSUE THREAD

**Issue by VE3IGS-Lyndon** [dg9vh/WSYSFDash#9]
Hello DG9VH from Lyndon (VE3IGS).  Firstly, thank you very much for developing this app!  I am putting together a YSF reflector for the South Georgian Bay Amateur Radio Club (SGBARC).  I have almost everything working but I am having trouble starting the logtailer.py program.  The problem looks a bit similar to a previous report but I have not been able to determine why my install is not working.  Here is some basic info:

 + Clean install of Debian 11 on a small Zotac computer.
 + The pYSFReflector is installed, tested and is working well.  Thanks!
 + I am using the lighttpd web server which is up and running (sgbarc.hopto.org).
 + The web page does not contain any usage data.
 + I am using the latest version of pYSFReflector and WSYSFDash.
 + After a reboot the logtailer.py does not appear to be running.
 + If I try to launch logtailer.py manually, I get an error.
 + The python3 version is Python 3.9.2
 + The python3-websockets version is 8.1-1.
 + I have installed the programs to /opt/pYSFReflector and /opt/WSYSFDash respectively.

At first, I was not using the python web server because lighttpd was working well.  I did add the **http.server.service** later in case this was needed in order for logtailer.py to work correctly.  However, I still could not start the logtailer service.

Here is the output of some commands after a reboot:

lyndon@zotac:~$ **ps -ef | grep python3**
root         476       1  0 12:33 ?        00:00:00 /usr/bin/python3 /usr/share/unattended-upgrades/unattended-upgrade-shutdown --wait-for-signal
mmdvm        484       1  0 12:33 ?        00:00:00 /usr/bin/python3 /opt/YSFReflector/YSFReflector /etc/YSFReflector/YSFReflector.ini
mmdvm        707       1  0 12:33 ?        00:00:00 /usr/bin/python3 -m http.server 8000 --directory /opt/WSYSFDash/html
lyndon      1179     935  0 12:41 pts/0    00:00:00 grep python3

lyndon@zotac:~$ **sudo runuser -u mmdvm /usr/bin/python3 /opt/WSYSFDash/logtailer.py**
2023-03-20 12:43:40,569 INFO Starting Websocketserver
Traceback (most recent call last):
  File "/opt/WSYSFDash/logtailer.py", line 200, in <module>
    main()
  File "/opt/WSYSFDash/logtailer.py", line 196, in main
    websocketserver()
  File "/opt/WSYSFDash/logtailer.py", line 180, in websocketserver
    if (config['DEFAULT']['Ssl'] == "True"):
  File "/usr/lib/python3.9/configparser.py", line 1254, in \_\_getitem\_\_
    raise KeyError(key)
KeyError: 'Ssl'

Here is the **YSFReflector.service** file:
[Unit]
Description=YSFReflector
After=network.target

[Service]
ExecStartPre=/bin/sleep 1
Type=simple
User=mmdvm
Group=mmdvm
Restart=always
`# Modify for different location of Python3 or location of files
ExecStart=/usr/bin/python3 /opt/YSFReflector/YSFReflector /etc/YSFReflector/YSFReflector.ini
[Install]
WantedBy=multi-user.target

Here is the **http.server.service** file:
[Unit]
Description=Python3 http.server
After=network.target

[Service]
ExecStartPre=/bin/sleep 10
Type=simple
User=mmdvm
Group=mmdvm
Restart=always
`# Modify for different location of Python3 or other port
ExecStart=/usr/bin/python3 -m http.server 8000 --directory /opt/WSYSFDash/html

[Install]
WantedBy=multi-user.target

Here is the **logtailer.service** file:
[Unit]
Description=Python3 logtailer for WSYSFDash
After=network.target

[Service]
ExecStartPre=/bin/sleep 10
Type=simple
User=mmdvm
Group=mmdvm
Restart=always
`# Modify for different location of Python3 or location of files
WorkingDirectory=/opt/WSYSFDash/
ExecStart=/usr/bin/python3 /opt/WSYSFDash/logtailer.py

[Install]
WantedBy=multi-user.target

Any help you can provide would be very much appreciated!
73,
Lyndon

**Comment by dg9vh** [comment]
Please post your logtailer.ini

Message ID: ***@***.***>
>


-- 
Amateurfunk ist das, was uns verbindet! Bleiben wir in Kontakt!
DARC e.V., Ortsverband Q03, Neunkirchen

**Comment by VE3IGS-Lyndon** [comment]
Thank you DG9VH for your quick response!

Here is my **logtailer.ini** file:

[DEFAULT]
\# No need to change this line below
Host=0.0.0.0
Port=5678
\# set to True if SSL will be used
Ssl=False
SslCert=/path/to/fullchain.pem
SslKey=/path/to/privkey.pem

\# This defines the maximum amount of loglines to be sent on initial opening of the dashboard
MaxLines=500

\# Keep this parameter synchrone to Filerotate in YSFReflector.ini - if 0 then False, if 1 then True
Filerotate=0

\# You can use the logtailer-Service for more than one reflector running on your system.
\# To do this, just copy the [YSFReflectorN]-Section into a new one, renumber it and modify the Logdir and Prefix.
\# To use this on systems with more than one reflector, it is recommended to use a real webserver to host the html-files.

[YSFReflector]
\# Localtion of your YSFReflector-binary
YSFReflector_bin=/opt/YSFReflector/YSFReflector

Logdir=/var/log/YSFReflector/
Prefix=YSFReflector

#[YSFReflector2]
#Logdir=/var/log/YSFReflector2/
#Prefix=YSFReflector

**Comment by dg9vh** [comment]
I have no idea, why this is happening... your setup does not differ from my test-setup as I can see...

**Comment by VE3IGS-Lyndon** [comment]
My web server is set up for http not https.  Could that be the problem?  I noticed that one of the lines in the error messages was:
KeyError: 'Ssl'

In my logtailer.ini I have: **Ssl=False**

I was surprised to see an Ssl error because I had set Ssl=False.  If I need to use SSL to get things working I then I can ahead and configure that.

**Comment by VE3IGS-Lyndon** [comment]
Here is the section of my **logtailer.py** that applies to the error above:

```
def websocketserver():
    start_server = None
    if (config['DEFAULT']['Ssl'] == "True"):
        ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
        cert_pem = config['DEFAULT']['SslCert']
        key_pem = config['DEFAULT']['SslKey']

        ssl_context.load_cert_chain(cert_pem, key_pem)
        start_server = websockets.serve(view_log, config['DEFAULT']['Host'], config['DEFAULT']['Port'], ssl=ssl_context)
    else:
        start_server = websockets.serve(view_log, config['DEFAULT']['Host'], config['DEFAULT']['Port'])

    asyncio.get_event_loop().run_until_complete(start_server)
    asyncio.get_event_loop().run_forever()


def main():
    logging.info("Starting Websocketserver")
    websocketserver()


if __name__ == '__main__':
    main()

```
I wish I could be of more help.  Unfortunately, I don't have much experience using Python.

**Comment by dg9vh** [comment]
Where is the logtailer.ini and your logtailer.py? Are both in the same directory and is logtailer.ini readable by user mmdvm?

**Comment by VE3IGS-Lyndon** [comment]
Here are the locations and permissions:
```
-rw-r--r-- 1 root root 943 Mar 20 08:10 /etc/WSYSFDash/logtailer.ini
-rw-r--r-- 1 root root 8.6K Mar 20 00:07 /opt/WSYSFDash/logtailer.py
```
With the following command:
sudo runuser -u mmdvm cat /etc/WSYSFDash/logtailer.ini
or
sudo runuser -u mmdvm cat /opt/WSYSFDash/logtailer.py

The contents of the respective files are displayed in the terminal window so they both are readable by the **mmdvm** user.

**Comment by dg9vh** [comment]
logtailer.ini and logtailer.py must resist in one and the same directory.

**Comment by VE3IGS-Lyndon** [comment]
Okay thanks, I now have **logtailer.ini** and **logtailer.py** in the same directory:
```
lyndon@zotac:/$ ll /opt/WSYSFDash/
total 16K
-rw-r--r-- 1 root root  943 Mar 20 17:07 logtailer.ini
-rw-r--r-- 1 root root 8.6K Mar 20 00:07 logtailer.py
```
Reboot...

I cannot see the logtailer in the process list:
```
lyndon@zotac:~$ ps -ef | grep python3
root         457       1  0 17:33 ?        00:00:00 /usr/bin/python3 /usr/share/unattended-upgrades/unattended-upgrade-shutdown --wait-for-signal
mmdvm        481       1  0 17:33 ?        00:00:00 /usr/bin/python3 /opt/YSFReflector/YSFReflector /etc/YSFReflector/YSFReflector.ini
mmdvm        703       1  0 17:33 ?        00:00:00 /usr/bin/python3 -m http.server 8000 --directory /opt/WSYSFDash/html
lyndon      1033     950  0 17:34 pts/0    00:00:00 grep python3
```
When I tried to run the program directly, I still get the following errors:
```
lyndon@zotac:~$ sudo -runuser -u mmdvm python3 /opt/WSYSFDash/logtailer.py 
2023-03-20 17:36:45,513 INFO Starting Websocketserver
Traceback (most recent call last):
  File "/opt/WSYSFDash/logtailer.py", line 200, in <module>
    main()
  File "/opt/WSYSFDash/logtailer.py", line 196, in main
    websocketserver()
  File "/opt/WSYSFDash/logtailer.py", line 180, in websocketserver
    if (config['DEFAULT']['Ssl'] == "True"):
  File "/usr/lib/python3.9/configparser.py", line 1254, in __getitem__
    raise KeyError(key)
KeyError: 'Ssl'
```

**Comment by dg9vh** [comment]
Just for a test, What happens,  if you run it directly as root?

**Comment by VE3IGS-Lyndon** [comment]
I still get the same error when running the program as root:
```
lyndon@zotac:~$ sudo /usr/bin/python3 /opt/WSYSFDash/logtailer.py 
2023-03-21 08:15:29,520 INFO Starting Websocketserver
Traceback (most recent call last):
  File "/opt/WSYSFDash/logtailer.py", line 200, in <module>
    main()
  File "/opt/WSYSFDash/logtailer.py", line 196, in main
    websocketserver()
  File "/opt/WSYSFDash/logtailer.py", line 180, in websocketserver
    if (config['DEFAULT']['Ssl'] == "True"):
  File "/usr/lib/python3.9/configparser.py", line 1254, in __getitem__
    raise KeyError(key)
KeyError: 'Ssl'
```

**Comment by dg9vh** [comment]
How did you edit the config file? With Windows-editor and then
transferred it to the system?

**Comment by VE3IGS-Lyndon** [comment]
No, everything was done on Linux.

**Comment by VE3IGS-Lyndon** [comment]
I was just able to get the logtailer running from the command line.  There were two problems that I was experiencing:

1. **The hidden .git directory was missing from my /opt/WSYSFDash directory.**  I did some of the installation from a remote computer using sftp:// and Nemo (a graphical file manager).  I missed copying the .git directory because it was not visible.
2. I also discovered that in order to start the logtailer program manually, **I had to 'cd' into the /opt/WSYSFDash directory first**.
```
lyndon@zotac:/$ cd /opt/WSYSFDash/

lyndon@zotac:/opt/WSYSFDash$ sudo /usr/bin/python3 logtailer.py
2023-03-21 08:46:40,167 INFO Starting Websocketserver
```
I was also able to manually run the program as the **mmdvm** user.

I will now try to get the logtailer program to start up automatically using the logtailer.service.

**Comment by VE3IGS-Lyndon** [comment]
The logtailer.py program is not loading automatically after a reboot.  I will redo the installation of WSYSFDash and report back here a bit later.

**Comment by VE3IGS-Lyndon** [comment]
Okay, I finally got everything going.  :)  I have some questions and suggestions that might make it a bit easier for people to successfully install the WSYSFDash software.

**1.  What is the correct cloning command?**

The installation instructions on the DG9VH website (https://www.dg9vh.de/) use this command to clone the software:
`git clone https://github.com/dg9vh/WSYSFDash`

However, the command in the README.md file shows this command:
`git clone --recurse-submodules -j8 https://github.com/dg9vh/WSYSFDash`

I checked the two downloads using **diff** and they are not the same.  So the question is... which command should be used for cloning the software?

**2.  Location of the logtailer.ini File**

The installation instructions on the DG9VH website show:
`sudo nano /etc/WSYSFDash/logtailer.ini`

That is why I ended up putting my logtailer.ini file in the /etc/ directory.  I didn't realize that it was likely a typo.  Maybe you could update that command to show /opt/ instead of /etc/.

**3.  Cloning Directly into /opt/ directory.**

When a user copies the WSYSFDash files to /opt/WSYSFDash, it is very easy to make a mistake and miss directories and files.  The first time I did this, I missed the hidden .git directory.  My suggestion would be to use sudo and clone directly into the /opt/ directory.  That would ensure that all of the required files are present.  After that is done, the ownership of all the directories and files could be changed to the user **mmdvm** (sudo chown -R mmdvm:mmdvm WSYSFDash).

**4.  logtailer.ini - Filerotate or FileRotate**

Just a small thing really... In the logtailer.ini file, I noticed:
`Filerotate=True`

This is a bit different than most of the other parameters so I wondered if it was correct?  Maybe it doesn't make any difference but I thought I would mention it.

**Thank You for the Software!**

Myself as well as all of the guys at my amateur radio club would like to thank you for writing this very useful software.  The dashboard looks great!  73

Lyndon - VE3IGS

**Comment by dg9vh** [comment]
> **1. What is the correct cloning command?**
`git clone --recurse-submodules -j8 https://github.com/dg9vh/WSYSFDash` - this is because there are some third-party-repositories to be cloned also. Howto on my website is modified to be similar now.

> **2. Location of the logtailer.ini File**
> 
> The installation instructions on the DG9VH website show: `sudo nano /etc/WSYSFDash/logtailer.ini`

updated. Was a typo. Don't ask me why :-)

> **3. Cloning Directly into /opt/ directory.**
> 
> When a user copies the WSYSFDash files to /opt/WSYSFDash, it is very easy to make a mistake and miss directories and files. The first time I did this, I missed the hidden .git directory. My suggestion would be to use sudo and clone directly into the /opt/ directory. That would ensure that all of the required files are present. After that is done, the ownership of all the directories and files could be changed to the user **mmdvm** (sudo chown -R mmdvm:mmdvm WSYSFDash).

In my opinion there are no dependencies in .git directory needed. On my reference installation it works without .git-directory. There must be something other wrong then.
 
> **4. logtailer.ini - Filerotate or FileRotate**
> 
> Just a small thing really... In the logtailer.ini file, I noticed: `Filerotate=True`
> 
> This is a bit different than most of the other parameters so I wondered if it was correct? Maybe it doesn't make any difference but I thought I would mention it.

By default, config-parser keys are not case sensitive as documented in https://docs.python.org/3/library/configparser.html#supported-ini-file-structure - so feel free to vary it :-) I will consider to change it after testing it myself, if there is any impact - but if you tested it successfully, you can give me feedback - actually I am very busy, so having this tested by third party would also be ok :-)

> **Thank You for the Software!**

No problem :-)

> Myself as well as all of the guys at my amateur radio club would like to thank you for writing this very useful software. The dashboard looks great! 73
> 
> Lyndon - VE3IGS

Mni tnx!

Best 73
Kim
DG9VH
